/**
 * Email Service for Sharing Reports with Doctors
 * Uses EmailJS or mailto fallback for sending emails
 */

import { formatDate, formatTime } from './patientDataManager';

/**
 * Share scan results with doctor via email
 * Uses mailto link as a simple implementation (can be upgraded to EmailJS/SendGrid)
 */
export const shareWithDoctor = (scanData, patientInfo, doctorEmail, doctorName) => {
  const subject = encodeURIComponent(
    `CT Scan Results for ${patientInfo.name} - ${formatDate(scanData.uploadTime)}`
  );

  const body = encodeURIComponent(
    `Dear ${doctorName},

I am sharing my recent CT scan results from PneumAI for your review.

PATIENT INFORMATION:
- Name: ${patientInfo.name}
- Patient ID: ${patientInfo.id}
- Age: ${patientInfo.age}
- Date of Birth: ${patientInfo.dateOfBirth || 'N/A'}

SCAN INFORMATION:
- Scan ID: ${scanData.scanId}
- Upload Date: ${formatDate(scanData.uploadTime)}
- Upload Time: ${formatTime(scanData.uploadTime)}
- Processing Time: ${scanData.processingTime || 'N/A'} seconds

ANALYSIS RESULTS:
- Detection Status: ${scanData.results.detected ? 'Abnormality Detected' : 'No Abnormalities Detected'}
- Risk Level: ${scanData.results.riskLevel.toUpperCase()}
- Confidence Score: ${(scanData.results.confidence * 100).toFixed(1)}%
- Classification: ${formatClassName(scanData.results.topClass)}

${scanData.results.detections && scanData.results.detections.length > 0 ? `
DETAILED FINDINGS (${scanData.results.detections.length} detection(s)):
${scanData.results.detections.map((det, idx) => `
${idx + 1}. ${formatClassName(det.class)}
   - Confidence: ${(det.confidence * 100).toFixed(1)}%
   - Location: (${Math.round(det.boundingBox?.x || 0)}, ${Math.round(det.boundingBox?.y || 0)})
   ${det.characteristics?.size_mm ? `- Size: ${det.characteristics.size_mm} mm` : ''}
`).join('\n')}
` : ''}

CLINICAL NOTES:
${patientInfo.clinicalNotes || 'No additional notes provided.'}

Please review these results at your earliest convenience. I am available for a consultation to discuss the findings and next steps.

You can access the full report and images through the PneumAI patient portal.

Best regards,
${patientInfo.name}
${patientInfo.email || ''}
${patientInfo.phone || ''}

---
This report was generated by PneumAI AI-Powered Lung Cancer Detection System.
This is an AI-generated analysis and should be reviewed by a qualified healthcare professional.
`
  );

  // Open mailto link
  window.location.href = `mailto:${doctorEmail}?subject=${subject}&body=${body}`;

  return true;
};

/**
 * Generate shareable link for scan results
 * In production, this would create a secure token-based link
 */
export const generateShareableLink = (scanId) => {
  const baseUrl = window.location.origin;
  const shareUrl = `${baseUrl}/shared-scan/${scanId}`;

  return shareUrl;
};

/**
 * Copy shareable link to clipboard
 */
export const copyShareableLink = async (scanId) => {
  const link = generateShareableLink(scanId);

  try {
    await navigator.clipboard.writeText(link);
    return { success: true, link };
  } catch (error) {
    console.error('Failed to copy link:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Send message to doctor through internal messaging system
 */
export const sendDoctorMessage = (message) => {
  // In production, this would send through API
  // For now, we'll simulate success
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        success: true,
        messageId: `msg_${Date.now()}`,
        sentAt: new Date().toISOString()
      });
    }, 1000);
  });
};

/**
 * Request appointment with doctor
 */
export const requestAppointment = (appointmentData) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        success: true,
        appointmentId: `appt_${Date.now()}`,
        status: 'pending',
        requestedAt: new Date().toISOString()
      });
    }, 1000);
  });
};

// Helper functions
const formatClassName = (className) => {
  if (!className) return 'N/A';
  return className
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

/**
 * Advanced: EmailJS Integration (requires EmailJS account and setup)
 * Uncomment and configure if you want to use EmailJS
 */

/*
import emailjs from '@emailjs/browser';

export const sendEmailViaEmailJS = async (scanData, patientInfo, doctorEmail) => {
  // Initialize EmailJS with your public key
  emailjs.init('YOUR_PUBLIC_KEY');

  const templateParams = {
    to_email: doctorEmail,
    patient_name: patientInfo.name,
    patient_id: patientInfo.id,
    scan_id: scanData.scanId,
    scan_date: formatDate(scanData.uploadTime),
    detection_status: scanData.results.detected ? 'Detected' : 'Not Detected',
    risk_level: scanData.results.riskLevel.toUpperCase(),
    confidence: (scanData.results.confidence * 100).toFixed(1),
    classification: formatClassName(scanData.results.topClass)
  };

  try {
    const response = await emailjs.send(
      'YOUR_SERVICE_ID',
      'YOUR_TEMPLATE_ID',
      templateParams
    );
    return { success: true, response };
  } catch (error) {
    console.error('EmailJS error:', error);
    return { success: false, error: error.message };
  }
};
*/
